# Generated by Django 4.2.4 on 2024-04-07 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "bookID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("authors", models.CharField(max_length=255)),
                ("language_code", models.CharField(max_length=10)),
                ("publisher", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LibraryMember",
            fields=[
                (
                    "memid",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("contact_number", models.CharField(max_length=15)),
                (
                    "membership_type",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Faculty", "Faculty"),
                            ("Guest", "Guest"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LibraryTransaction",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("returndate", models.DateField()),
                ("issuedate", models.DateField()),
                ("condition", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("Issued", "Issued"), ("Returned", "Returned")],
                        max_length=50,
                    ),
                ),
                (
                    "bookid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="database.book"
                    ),
                ),
                (
                    "memberid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.librarymember",
                    ),
                ),
            ],
        ),
    ]
