# Generated by Django 4.2.4 on 2024-04-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="librarymember",
            old_name="name",
            new_name="book_name",
        ),
    ]
