# Generated by Django 4.2.4 on 2024-04-07 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_rename_name_librarymember_book_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="librarymember",
            old_name="book_name",
            new_name="name",
        ),
    ]
